#  gcloud builds submit --substitutions SHORT_SHA="banana_$(git rev-parse --short=7 HEAD)" .
steps:

  - name: 'golang'
    id: Test
    args: ['go','test', './...']
  - name: 'golang'
    id: Compile
    args: ['go','build', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: Log
    args:
      - '-c'
      - |
        ls -la ; env
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA'
options:
  volumes:
    - name: go-modules
      path: /go
  env:
    - GO111MODULE=on
    - ROOT_PROJECT=github.com/viggin543/gke-gitops-tutorial-cloudbuild